---
title: "Statistics with R: Course Outline"
author: "SRCBD"
date: \today
output: 
  pdf_document:
    toc: true
    toc_depth: 2

---

# Week 01: Getting Started with Statistics and R

- **Session 01:** What is Statistics? Statistics vs Data Science; Statistics vs Mathematics; Why R? Who Use R? Who Developed R? Other Languages; Install R and Rstudio; Start Writing R Code (Windows, Linux, and Command Line); Effectively Using Rstudio; R Script; R Documentation (Help); Handling Error; R Packages; R Mathematical Operations; Variables; Data Types;

- **Session 02:** Vector, Matrix, List, and Data Frame; Functions (When and Why); Loops (Alternatives and Comparison with Other Languages); Apply family (apply, lapply, sapply, etc.). 


# Week 02: Data Manipulation (Base R and tidyverse)

- **Session 01:** Reading Data from Different Files (Base R, tidyverse, and data.table way); Switching to And from Excel, Stata, and SPSS; Instant Copy from Excel and Should One Do So? Handling Missing Values;  Concept of Tidy Data; How to Make Data Tidy? Subsetting/Filtering Data; Pipe Operator; Piping Output to Plots; Selecting Rows and Columns.

- **Session 02:** Transforming Data; Summarizing Data; Relational Data (e.g, Merging Tables); Comparison of SQL And R for Relational Database. 

# Week 03: Basic Statistics, Charts, and Curves; 

- **Session 01:** Measures of Central Tendency and Dispersion (Averages, Quartiles, Variance, etc.); Correlation; Correlation Plot; Pie Chart; Bar Chart; Chart Characteristics (color, title, axes etc.); How to Use Proper Legends? 

- **Session 02:** Histogram; Ogive (and how to interpret it); Boxplot; Time Series Plots/Line Chart; Scatter Plot; Equation and Curves; Love Equation and Curve; Different Ways of Coloring Plots, including RColorBrewer; Wordcloud; Comparison of Suitability of Plots.  


# Week 04: Data Visualization with ggplot2

- **Session 01:** How ggplot2 works; Different geoms and aesthetics; Pie Chart; Bar Chart; Histogram; Boxplot; Scatter Plot; Time Series Plots/Line Chart; Trends within Plots; Piping Output to ggplot2.

- **Session 02:** Correlogram; Themes and Legends; Doughnut Chart; Density Chart; Violin Chart; Bubble Chart; Spider/Radar Chart; Lollipop Chart; Area Chart; Attaching Texts to Plots; Advanced Customization And Attaining What Seems Improbable. 

# Week 05: Modeling with R 

- **Session 01:** Correlation and Regression; Interpretation of Results; Multiple Linear Regression; Regression with Specified Intercept; Choosing between Models; Poisson Regression; Logistic Regression; Prediction.

- **Session 02:** When to Use Which Regression (with Examples); Time Series Analysis; Confidence Interval; Test of Hypothesis (including Z-test, t-test, Chi-squared tests).  

# Week 06: Mapping with R

- **Session 01:** Acquiring Data for Mapping; Retrieving Data from Google Map; Choropleth Map; Different Ways to Make a Choropleth; 

- **Session 02:** Plotting Points on Map; Animated Map; Misc. 
