# (PART) Presentations {-}

# Presentations {- #pres} 

### How to Use {- #how}

- Press `space` to go the next slide.
- Press up-arrow ($\uparrow$) or `P` to go the previous slide.

See more [here](https://defkey.com/reveal-js-shortcuts)

### Statistics {- #stat_pres}

**First Part: Statistics**

- Chapter 01: [Introduction](https://lecture.statmania.info/stat/ch1_xi_stat.html)
- Chapter 02: [Collection, Presentation, and Organization of Data](https://lecture.statmania.info/stat/ch2_xi_stat.html)
- Chapter 03: [Measures of Central Tendency](https://lecture.statmania.info/stat/ch3_xi_stat.html)
- Chapter 04: [Measures of Dispersion](https://lecture.statmania.info/stat/ch4_xi_stat_dispersion.html)
- Chapter 05: [Moments, Skewness, and Kurtosis](https://lecture.statmania.info/stat/ch5_xi_stat_moments_skewness_kurtosis.html)
- Chapter 06: [Correlation and Regression](https://lecture.statmania.info/stat/ch6_xi_statcorrelation_regression.html)
- Chapter 07: [Time Series](https://lecture.statmania.info/stat/ch7_xi_time_series.html)

**Second Part: Probability**

- Chapter 01: [Introduction to probability](https://lecture.statmania.info/stat/prob_ch1_intro.html#/)
- Chapter 02: [Random variable and Probability Distributions](stat/prob_ch2_random_variable.html)
- Chapter 03: [Mathematical Expectation](stat/prob_ch3_expectation.html)
- Chapter 04: [Binomial Distribution](stat/prob_ch4_binomial_dist.html)
- Chapter 05: [Poisson Distribution](stat/prob_ch5_poisson_dist.html)

**Others**

- [In the world of Paradoxes](stat/paradoxes.html)

**Elementary Statistics**

- [Elementary Statistics](https://lecture.statmania.info/math/stat_preliminaries.html)

### Mathematics {- #math}

**Higher Secondary**
 
- [Dispersion and Probability](https://lecture.statmania.info/math/xi_math_probability.html)
- [Permutation and Combination](https://lecture.statmania.info/math/xi_math_perm_comb.html)

**Class IX-X**

- [Statistics](https://lecture.statmania.info/math/x_stat.html)
- [Probability](https://lecture.statmania.info/math/x_prob.html)

**Class Eight**

- [Mathematics Exercises](https://lecture.statmania.info/math/viii_math_exercise.html)
- [Algebra](https://lecture.statmania.info/math/viii_math_algebra.html)

**Class Seven**

- [Algebra All Chapters](https://lecture.statmania.info/math/vii_math_algebra.html)
- [Mathematics Exercises](https://lecture.statmania.info/math/vii_math_exercise.html)
- [Chapter 7.3](https://lecture.statmania.info/math/vii_math_7.3.html)

### Questions {-}

```{bash, echo =  FALSE}
ls docs/stat/question | grep pdf > docs/stat/question/ques.csv
```

```{r, echo=FALSE}
ques <- read.csv("docs/stat/question/ques.csv", header = FALSE)
ques <- paste0("<https://lecture.statmania.info/stat/question/",ques$V1,">")
write.csv(ques, file = "docs/stat/question/qlinks.csv", row.names = FALSE)
```

```{bash, echo =  FALSE, comment=NA}
cat docs/stat/question/qlinks.csv | sed 1d | sed 's/"/ /g' > docs/stat/question/q.md
```

<iframe width="100%" frameborder="0" src="stat/question/q.md"></iframe>
