---
title: "VII Math Exercises"
author: Abdullah Al Mahmud
date: \today
output: 
  revealjs::revealjs_presentation:
    theme: sky
    reveal_plugins: ["menu", "chalkboard", "zoom"]
    self_contained: false
    css: css/styles.css
    includes:
      in_header: css/header.html
---

# Chapter 4.1

## Multiply (20)

$x^2+2x-3, x+3$

## Multiply (24)

$y^2-y+1, 1+y+y^2$

## Problem 25

If $A=x^2+xy+y^2$ and $B=x-y$, $AB=?$

# Chapter 4.2

## Divide

$2x^2-7xy+6y^2$ by $x-2y$

> - $16x^4+36x^2+81$ by $4x^2-6x+9$


# Chapter 5.1

## Expand (28)

Expand $x^4-y^4$

## Extra

i. $a^m \cdot a^{-n}=?$
ii. If a = 3 and m = n = 2, $a^m \cdot (a^n)^m=?$
iii. $a^m \cdot a^n \cdot a^{mn}=?$

## Determine square
3x-2y+5z

## Find

If $m^2-2m+1=0$, prove $m^4+\frac 1 {m^4}=2$

> - First, find the value of $m+\frac 1 m$
> - Squaring on both sides
> - $m^2+2+\frac 1 {m^2}=4$

> - There is another method

## Simplify

$(2a+1)^2-4a(2a+1)+4a^2$

Solve directly or by assuming something

# Chapter 5.2

## Multiply (6)

(10-xy)(10+xy)

## Multiply (10)

$(a^4+3a^2x^2+9x^4)(9x^4-3a^2x^2+a^4)$

## Multiply (11)

$(x+a)(x-1)(x^2+1)$

# Chapter 5.3

## Resolve into Factors (2)

$a^2+bc+ca+ab$

## Resolve into Factors (8)

$a^2-(x+y)^2$

## Resolve into Factors (12)

$y^2-6y-91$

## Resolve into Factors (20)

$4x^2+12xy+9y^2-16a^2$

## Resolve into Factors (Extra 01)

$15x^2-14x-8$

## Resolve into Factors (Extra 02)

$2bd-a^2-c^2+b^2+d^2+2ac$

## Creative Questions (01)

*The length of a rectangular garden is three times its breadth. The perimeter of the garden is 96 meter.*

<small>

a. Form the equation, assuming breadth as x.
b. Find the length and breadth of the garden. 
c. If the cost of trimming grass is 8 tk. per square meter, how much money will be needed to trim grass of the entire garden? 

</small>

<div onclick="klikaj('cq1')"><span>Answer</span></div>
<div id="cq1" style="visibility: hidden">
> - 1. $2(3x+x)=96$
> - 2. $8x=96 \therefore x = \frac {96} 8 =$ `r 96/8` = (breadth)
> - 3. Area = `r 12*36`, Cost = `r 12*36*8` tk. 
</div>
<script>
function klikaj(i) {
    document.getElementById(i).style.visibility='visible';
}
</script>

## Creative Questions (02)

*The breadth of a rectangular space is one-forth its length.*

a. If the length is x, express the perimeter of the space in terms of x.
b. If the perimeter of the garden is 40 meter, what are the length and breadth of the garden?
c. If the total cost of cleaning the garden is 1500 tk, what will be the cost to clean per square meter of the garden? 


## Creative Questions (03)

The summation of three consecutive numbers is 153. 

a. If the lowest number is x, what is the next number?
b. Form the equation. 
c. Find the numbers. 

# Statistics

The following are temperature of a certain location in November. 


`r set.seed(100); sample(28:35, 30, replace = TRUE)`

a. What is data?
b. Make a frequency distribution (using 6 classes) from this data and interpret.
c. Make a histogram and interpret. 


## Thanks

<center>

Visit 

<https://lecture.statmania.info>

to see all lecture slides. 

</center>