---
title: "Mathematics (VII"
author: Abdullah Al Mahmud
date: \today
output: 
  revealjs::revealjs_presentation:
    theme: sky
    reveal_plugins: ["menu", "chalkboard"]
    self_contained: false
    css: css/styles.css
    includes:
      in_header: css/header.html
---
# Exercise

$x-\frac{1}{x}=4$, $x^2+\frac{1}{x^2}=?$

> - $x^4+\frac{1}{x^4}=?$

## Express as difference of squares

(2x+3)(4x-5)

## Find

a+b=5, a-b=3

Find $2a^2+2b^2$ and ab; which one is bigger? 

# Chapter 4.3

## Problem # 01
Resolve into factors 

$3x-75x^3$

## Problem # 04

$a^2-2ab+b^2-p^2$

## Problem # 06
$8a+ap^3$

## Problem # 10

$x^4-6x^2+1$

## Problem # 16

$x^2+7x-120$

## Problem # 18

$a^2+7ab+12b^2$

## Problem # 21

$(x^2-x)^2+3(x^2-x)-40$

## Problem # 24

$x^2+(3a+4b)x+(2a^2+5ab+3b^2)$

> - $x^2+(3a+4b)x+(2a+3b)(a+b)$
> - $x^2+(2a+3b)x+(a+b)x+(2a+3b)(a+b)$

## Problem # 26

$x^2-x-(a+1)(a+2)$

> - $x^2-(a+2)x+(a+1)x-(a+1)(a+2)$

## Problem # 33

$2(x+y)^2-3(x+y)-2$

> - $2(x+y)^2-4(x+y)+(x+y)-2$


## Problem # 34

$ax^2+(a^2+1)x+a$

# Chapter 4.4

## Find HCF (# 12)

$36a^2b^2c^4d^5, 54a^5c^2d^4, and \space 90a^4b^3c^2$

## Find HCF (# 16)

$x^2-3x, x^2-9, x^2-4x+3$

## Find HCF (# 18)

$a^2b(a^3-b^3), a^2b^2(a^4+a^2b^2+b^4), (a^3b^2+a^2b^3+ab^4)$

## Find HCF (# 19)

$a^3-3a^2-10a, a^3+6a^2+8a, a^4-5a^3-14a^2$

## Find LCM (# 21)

$5a^2b^3c^2,10ab^2c^3, 15ab^3c$

## Find LCM (# 24)

$x^2+3x+2, x^2-1, x^2+x-2$

## Find LCM (# 26)

$6x^2-x-1, 3x^2+7x+2, 2x^2+3x-2$

## Problem # 28

If $x^2+\frac{1}{x^2}=3$ find 

a. $(x+\frac{1}{x})^2$
b. $\frac{x^6+1}{x^3}$
c. $(x^2+\frac{1}{x^2})^3$


# Chapter 5.1

## Express in LOwest Form #01

$\frac{4x^2y^3z^5}{9x^5y^2z^3}$

## Express in common denominator

$\frac{x-y}{xy}, \frac{y-z}{yz}, \frac{z-x}{zx}$

## ADD

$\frac{a}{bc}, \frac{b}{ca}, \frac{c}{ab}$

## ADD (3.g)

$\frac{1}{x-2}+\frac{1}{x+2}+\frac{4}{x-4}$

> - LCM = $(x-2)(x+2)=(x^2-4$

## Add (3.h)

$\frac{1}{x^-1}+\frac{1}{x^4-1}+\frac{1}{x^8-1}$

> - $x^8-1=(x^4+1)(x^4-1) = (x^4+1)(x^2+1)(x^2-1)$
> - LCM = $(x^4+1)(x^2+1)(x^2-1)$

## Find Difference (4.b)

$\frac{1}{y(x-y)}-\frac{1}{x(x+y)}$

## Find Difference (4.c)

$\frac{x+1}{1+x+x^2}-\frac{x-1}{1-x+x^2}$

- It is better to write LCM in long form. 
- LCM = $(1+x+x^2)(1-x+x^2)$
- Short form: $(1+x^2)^2-x^2$

## Find Difference (4.e)

$\frac{1}{x-y}-\frac{x^2-xy+y^2}{x^3+y^3}$

## Simplify (5.b)

$\frac{x-y}{(x+y)(y+z)}+\frac{y-z}{(y+z)(z+x)}+\frac{z-x}{(z+x)(x+y)}$

## Simplify (5.g)

$\frac{1}{x-1}-\frac{1}{x+1}-\frac{2}{x^2+1}+\frac{4}{x^4+1}$

- LCM in short form: $x^8-1$; guess how?

# Chapter 5.2

## Divide 

$\frac{x^2+3x-4}{x^2-7x+12}$ by $\frac{x^2-9}{x^2-16}$

> - Answer: $\frac{(x-a)(x-3)}{(x-4)^2}$ wrong

## Multiply (6.g)

$\frac{x^2-3x+2}{x^2-4x+3}, \frac{x^2-5x+6}{x^2-7x+12}, \frac{x^2-16}{x^2-9}$

> - Answer: $\frac{(x-2)^2(x+4)}{(x-3)^2(x+3)}$

## Multiply (6.i)

$\frac{x^3+y^3}{a^2+ab^2+b^3}, \frac{a^3-b^2}{x^2-xy+y^2}, \frac{ab}{x+y}$

> - Answer: $ab(a-b$

## Divide (7.f)

$\frac{x^3-y^3}{x+y}$ by  $\frac{x^2+xy+y^2}{x^2-y^2}$

> - Answer: $(x-y)^2$

## Simplify (8.c)

$(1-\frac c {a+b})(\frac a {a+b+c}-\frac a {a+b-c})$

> - Answer: $\frac{-2ca}{(a+b)(a+b+c)}$

## Simplify (8.f)

$(\frac{2x+y}{x+y}-1) \div (1-\frac y {x+y})$

> - Answer: 1

## Simplify (8.g)

$(\frac a {a+b}-\frac b {a-b}) \div (\frac a {a-b} - \frac b {a+b})$

> - Answer: 1


# Creative questions

## Creative Question -01

Observe the pair of equations below:

- $x + ay = b ... (i)$ 
- $ax-by=c... (ii)$

a. Of which equations is the solution $(b,0)$?
b. If $a=1, b=2, c = 3$, solve the pair of equations.
c. Solve the given pair of equations by using eliminations method. 

## Creative -02

5 years ago the ratio of ages of father and son was 7:1 and after 10 years, the ratio would be 5:2

a. Form two equations with two variables. 
b. Find the present ages of father and son.
c. Form an equation with one variable and calculate the present age of father and son. 

## Creative -03

Thrice of sum of two numbers is 17 and sum of the first and thrice of the second is 19. 

a. Form two equations.
b. Solve by substitution method.
c. Solve by means of graph (without using (2)).
