---
title: "Mathematics (VIII)"
author: Abdullah Al Mahmud
date: \today
theme: sky
output: 
  revealjs::revealjs_presentation:
    incremental: false
    reveal_plugins: ["chalkboard", "menu"]
    self_contained: false
    slideNumber: true
    css: css/styles.css
    includes:
      in_header: css/header.html
---

# Chapter 04: Algebraic Formula & Application

## Keep in Mind!

- Read The Text Book Thoroughly
- Read Concepts Carefully
- Think Why Formulae Are Such
- DO NOT MEMORIZE Formulae

## Formulae

### ~~MEMORIZE~~ FEEL



<div class="container">
<div class="col">
#### Can you translate them into English?

- $(a+b)^2 = a^2+2ab+b^2$
- $(a-b)^2 = a^2-2ab+b^2$
- $a^2-b^2=(a+b)(a-b)$
</div>
<div class="col">
#### Corollary
<small>

- $a^2+b^2= ?$ 
- $a^2+b^2= ?$ (in another form)
- $(a+b)^2 = ?$ (in terms of) $(a-b)^2$
- $(a-b)^2 = ?$ (in terms of) $(a+b)^2$
- $(a+b)^2+(a-b)^2 = ?$
- $(a+b)^2+(a-b)^2 = ?$
- $ab=?$

</small>
</div>
</div>

## Relationship between (a+b)^2^ and (a-b)^2^

\begin{eqnarray} 
(a+b)^2 &=& a^2+2ab+b^2     \nonumber \\
&=& a^2-2ab+b^2 + 2ab + 2ab \nonumber \\
&=& (a-b)^2 +4ab   \nonumber \\
\end{eqnarray}

>- Find (a-b)^2^ similarly

## Find Squares

> - (2x+y)
> - (5m-3p)
> - ax+b+2

## 2(a)

Simplify

$(x+y)^2+2(x+y)(x-y)+(x-y)^2$


## 2(d)

Simplify

$(8x+y)^2 - (16x+2y)(5x+y) + (5x+y)^2$

> - $(8x+y)^2 - 2(8x+y)(5x+y) + (5x+y)^2$

## 3(a)

Find product using formula

(x+7)(x-7)

## 3(b)

Find product using formula

(5x+13)(5x-13)

## 3(i)

(ax-by+cz)(ax+by-cz)

> - {ax-(by-cz)}{ax+(by-cz)}
> - $(ax)^2-(by-cz)^2=a^2x^2-b^2y^2+2bycz-c^2z^2$

## Application of $x^2+x(a+b)+ab$



\begin{eqnarray} 
Expression (x+3)(x+4)     \nonumber \\
&=& \\
\end{eqnarray}

## 3(l)

Formula: (x+a)(x+b) = x^2+x(a+b)+ab

## Find Value (5)

If $x-\frac 1 x=3$, $x^2+\frac 1 {x^2}=?$

<div class="container">
<div class="col">
<div onclick="klikaj('51')"><span>Solution 01</span></div>
<div id="51" style="visibility: hidden">
$x^2+\frac 1 {x^2}=(x-\frac 1 x)^2 + 2 \cdot x \cdot \frac 1 x$
</div>
<script>
function klikaj(i) {
    document.getElementById(i).style.visibility='visible';
}
</script>
</div>
<div class="col">
<div onclick="klikaj('52')"><span>Alternative</span></div>
<div id="52" style="visibility: hidden">
Given 

$x-\frac 1 x = 3$

$x^2-2 \cdot x \cdot \frac 1 x + \frac 1 {x^2}$

$\therefore x^2+\frac 1 {x^2} = 9+2 = 11$
</div>
<script>
function klikaj(i) {
    document.getElementById(i).style.visibility='visible';
}
</script>
</div>
</div>

## Find Value (6)

$a+\frac 1 a =4, a^4+\frac 1 {a^4}=?$

<div class="container">
<div class="col">
<div onclick="klikaj('61')"><span>Answer</span></div>
<div id="61" style="visibility: hidden">
?
</div>
<script>
function klikaj(i) {
    document.getElementById(i).style.visibility='visible';
}
</script>
</div>
<div class="col">
<div onclick="klikaj('62')"><span>Answer</span></div>
<div id="62" style="visibility: hidden">
?
</div>
<script>
function klikaj(i) {
    document.getElementById(i).style.visibility='visible';
}
</script>
</div>
</div>

## Find Value (7)

If m = 6 and n = 7

$16(m^2+n^2)^2+56(m^2+n^2)(3m^2-2n^2)+49(3m^2-2n^2)^2$

## Find Value (8)

$a-\frac 1 a=m$ 

Show $a^4+\frac 1 {a^4}=m^4+4m^2+2$

## Express as difference of squares (13a)

i. (5 p - 3q)( p + 7q)
ii. (5x - 13)(5x + 13)

<div class="container">
<div class="col">
<div onclick="klikaj('13a1')"><span>Solution</span></div>
<div id="13a1" style="visibility: hidden">
<small>
Let 

a = 5p-3q and b = p+7q


\begin{eqnarray} 
ab &=&(\frac{a+b}2)^2-(\frac{a-b}2)^2     \nonumber \\
 &=& (\frac{5p-3q+p+7q}2)^2-(\frac{5p-3q-p-7q}2)^2 \nonumber \\
&=&  (\frac{6p+4q}2)^2-(\frac{4p-10q}2)^2   \nonumber \\
&=& (3p+2q)^2-(2p-5q)^2   \nonumber \\
\end{eqnarray}
</small>
</div>
<script>
function klikaj(i) {
    document.getElementById(i).style.visibility='visible';
}
</script>
</div>
<div class="col">
Solution (ii)

> - $(5x)^2-(13)^2$
</div>
</div>

## Find Value (9)

$x-\frac 1 x=4$; Prove $x^2+(\frac 1 x)^2=18$

\begin{eqnarray} 
x-\frac 1 x=4      \nonumber \\
&\Rightarrow& x^2-2 + \frac 1 {x^2} = 16 \nonumber \\
&\Rightarrow& x^2+   \frac 1 {x^2} =16+2=18 \nonumber \\
\end{eqnarray}

# Chapter 4.2 

## Formulae

<div class="container">
<div class="col">
a. $(a+b)^3=a^3+3a^2b+3ab^2+b^3$
a. $(a-b)^3=a^3-3a^2b+3ab^2-b^3$
c. $a^3+b^3=?$ (Find from above)
c. $a^3-b^3=?$ (Find from above)
</div>

<div class="col">

<small>

> - $a^3+b^3=(a+b)^3-3ab(a+b)$ (Rearrange)
> - $a^3-b^3=(a-b)^3+3ab(a-b)$ (Rearrange)
> - $a^3+b^3=(a+b)(a^2-ab+b^2)$
> - $a^3-b^3=(a-b)(a^2+ab+b^2)$

</small>
</div>
</div>


## Find Cubes

<div class="container">
<div class="col">
a. 2a+5b 
c. $a^2b^2-c^2d^2$
d. $(2m+3n-5p)^2$
</div>
<div class="col">
> - 1.$8a^3+6a^2b+150ab^2+125b^3$
</div>
</div>

## Simplify

<small>



<div class="container">
<div class="col">
a. $(3x+y)^3+3(3x+y)^2(3x-y)+3(3x+y)(3x-y)^2+(3x-y)^3$
b. $(6m+2)^3-3(6m+2)^2(6m-4)+3(6m+2)(6m-4)^2+(6m-4)^3$
</div>
<div class="col">
> - 1. $216x^3$
> - 2. 216
</div>
</div>
</small>

## Find Value(s)

<small>

<div class="container">
<div class="col">
a. If a+b=8 and ab=15, $a^3+b^3=?$
b. 2x+3y=13 and xy=6, $8x^3+27y^3$
c. $x-2y=3, x^3-8y^3-18xy=?$ 
d. $4x-3=5, 64x^3-27-180x=?$
e. $x=5, x^3-12x^2+48x-64=?$
f. $x+\frac 1 x = 4, x^3+\frac 1 {x^3}=?$
g. $a^2-1-5a=0, a^3-\frac 1 {a^3}=?$

</div>

<div class="col">
> - $152$
> - $(2x+3y)^2-3 \cdot 2x \cdot 3y \cdot (2x+3y) = 13^2-3 \cdot 6 \cdot 6 \cdot 13 = 793$
> - $(x-2y)^3+3 \cdot x \cdot 2y (x-2y) - 18xy = 3^3+18xy-18xy=27$
> - $125$
> - $x^3-3x^2 \cdot 4 + 3x\cdot 4^2-4^3=(5-4)^3=1$
> - $4^3-3 \times 4 = 64-12 = 52$
> - $a-\frac 1 a = 5, \therefore Answer=5^3+3 \times 5=140$

</div>
</div>

</small>

## Find Products Using Formula
<small>
<div class= "box">
- $a^3+b^3=(a+b)(a^2-ab+b^2)$
- $a^3-b^3=(a-b)(a^2+ab+b^2)$
</div>

<div class="container">
<div class="col">

Find 

a. $(a^2+b^2)(a^4-a^2b^2+b^4)$
b. $(ax-by)(a^2x^2+abxy+b^2y^2)$
c. $(x^2+a)(x^4-ax^2+a^2)$
d. $(x+a)(x^2-ax+a^2)(x-a)(x^2+ax+a^2)$
e. $27x^4-8xy^3$
f. $27a^3-8$
</div>

<div class="col">
Answers

> - $a^6+b^6$
> - $a^3x^3-b^3y^3$
> - $x^6+a^3$
> - $x^6-a^6$
> - $x(27x^3-8y^3)=\cdots=x(3x-2y)(9x^2+6xy+4y^2)$
> - $(3a)^3-2^3=\cdots$
</div>
</div>
</small>

## Find Values

<small>
<div class="container">
<div class="col">
a. a+b=3, ab =2; $a^3+b^3=?$
b. x+y=4, $x^3+y^3+12xy=?$
c. $a+\frac 1 a = 7, a^3+\frac 1 {a^3}=?$
d. m = 2; $27m^3+54m^2+36m+8=?$
e. a = -3, b = 2; Find $8a^3+36a^2b+54ab^2+27b^3$
f. $a^2+b^2=c^2; a^6+b^6+3a^2b^2c^2=?$
g. $a^2-a-6=0, a^3+\frac 1 {a^3}=?$

</div>
<div class="col">
> - $3^3 - 3 \times 2 \times 3 = 9$
> - $7^3-3 \times 7$ = 343-21=322
> - $(x+y)^3-3xy(x+y)+12xy=4^3=64$
> - $(3m)^3+3\cdot (3m)^2 \cdot 2 + \cdots = (3m+2)^3=8^3=512$
> - $=\cdots = (2a+3b)^3=(-6+6)^3=0$
> - $c^6$
> - $a^2-a-6=0 \Rightarrow a^2-3a+2a-6=0 \Rightarrow a=3,-2$ 
  $\Rightarrow a+\frac 1 a = 3 + \frac 1 3 = \frac {10} 3$ or $\cdots$
 
  
</div>
</div>
</small>

# Chapter 4.3

## Resolve into Factors

<small>
<div class="container">
<div class="col">
1. $x^2-15x+54$
2. $x^2-23x+132$
3. $2x^2+9x+10$
4. $8x^2+42x+27$
5. $16y^2-a^2-6a-9$
6. $(x-y)^3+z^3$
7. $(x^2-x)^2+3(x^2-x)-40$
8. $x^2+(3a+4b)x+(2a^2+5ab+3b^2)$
9. $x^2-x-(a+1)(a+2)$
10. $ax^2+(a^2+1)x+a$
11. $a^3-3a^2b+3ab^2-2b^3$
</div>
<div class="col">

> - 1. (x-6)(x-9)
> - 2. (x-12)(x-11)
> - 3. (x+2)(2x+5)
> - 4. $(36,6) \Rightarrow (4x+3)(2x+9)$
> - 5. $(4y)^2-(a+3)^2=()()$
> - 6. Use $(a+b)(a^2-ab+b^2)$
> - 7. Assume $(x^2-x)^2=a$ or continue directly.
> - 8. $x^2+(3a+4b)x+(2a+3b)(a+b)$
> - 9. $x^2-(a+2)x+(a+1)x-(a+1)(a+2)$ or let a+1=p
> - 10. $ax^2+a^2x+x+a \rightarrow ax(x+a)+1(x+a) \rightarrow ()()$ 
> - 11. $a^3-3a^2b+3ab^2-b^3-b^3 \rightarrow (a-b)^3-b^3 \rightarrow \cdots (a-2b)(a^2-ab+b^2)$
  
</div>
</div>
</small>

# Chapter 4.3: LCM & HCF

## What LCM & HCF they Mean

<small>
<div class="container">
<div class="col">
LCM = Lowest Common **Multiple**

Numbers: 12, 18

**Multiples of 12:** 12, 24, <u>36</u>, 48, 60

**Multiples of 18:** 18, <u>36</u>, 54, 72, 90

Lowest Common Multiple, LCM = 36

12 = $2 \times 2 \times 3$

18 = $2 \times 3 \times 3$

LCM = $2 \times 2 \times 3 \times 3 = 36$

</div>
<div class="col">

<div onclick="klikaj('hcf')"><span>HCF</span></div>
<div id="hcf" style="visibility: hidden">
Highest Common Factor/Divisor
</div>
<script>
function klikaj(i) {
    document.getElementById(i).style.visibility='visible';
}
</script>
</div>
</div>

</small>