---
title: ''
output:
  pdf_document: default
  html_document: default
  word_document: default
---
\begin{center}
\begin{large}
Pabna Cadet College
\end{large}

Fortnightly Examination - 2021

Third Term Second Phase 

Subject: Statistics

Class: XII
\end{center}

Time: 25 minutes
\hfill
Full Marks: 10

Answer all the questions.

1. The probability density function of x is given below

$$
  f(x) =
\begin{cases}
\frac 3 4 (x^2+1),  & 0 \le x \le 1 \\
0, & otherwise
\end{cases}
$$

a. In a probability density function (pdf), what is the probability of a single value?
b. Verify whether the given function is a probability density function.
c. Find $P(0\le X \le 0.6)$
d. Find the first quartile of the pdf.

&nbsp;
&nbsp;


\begin{center}
\begin{large}
Pabna Cadet College
\end{large}

Fortnightly Examination - 2021

Third Term Second Phase 

Subject: Statistics

Class: XII
\end{center}

Time: 25 minutes
\hfill
Full Marks: 10

Answer all the questions.


1. The probability density function of x is given below

$$
  f(x) =
\begin{cases}
\frac 3 4 (x^2+1),  & 0 \le x \le 1 \\
0, & otherwise
\end{cases}
$$

a. In a probability density function (pdf), what is the probability of a single value?
b. Verify whether the given function is a probability density function.
c. Find $P(0\le X \le 0.6)$
d. Find the first quartile of the pdf.
