---
title: ''
classoption:
- twocolumn
output: html_document
---
<div style="font-weight: bold;">
<center><h5>Pabna Cadet College</h5></center>

<center>Test Examination - 2021<center>
<center>Class: XII</center>
<center>Subject: Statistics 2^nd^ Paper (Creative)</center> 

<div style="float: left">Time: 2 hours and 35 minutes</div>
<div style="float: right">Full Marks: 50</div>
<div style="margin: 0 auto; width: 100px;">Sub Code: 130</div>
<div style="float: left">Figures in the right indicate full marks. Answer five questions, taking at least two from each group</div>
</div>

.

:::: {style="display: grid; grid-template-columns: 1fr 1fr; grid-column-gap: 10px;"}

::: {}
<center><h6>**Group A**</h6></center>

**1. It is observed that in a college, there are 100 students, of whom 30 play football, 40 play cricket, and 20 play both.**

a. What is a sample space?
b. What is the relationship between independence and mutual excluvity? 
b. Are the probabilities of playing cricket and that of football independent? Prove.
c. If a student is selected randomly,a nd if he plays cricket, what is the probability that he does not play football?

**2. For a lottery, 9 red and 7 white balls are placed in a box. Different combinations of balls are then picked up from the box.**

a. What is the probability of an impossible event?
b. If a ball is drawn, what is the probability the ball not white?
c. If 6 balls are picked randomly, what is the probability that 3 balls are red and 3 balls are white?
d. When two balls are drawn without replacement, what is the probability that none is red? If this task is repeated a hundred times, approximately how many times would we get all-non-red balls?

**3. The probability density function of a continuous random variable is**

$$
  f(x) =
\begin{cases}
kx^2+kx+ \frac 18,  & 0 \le x \le 2 \\
0, & otherwise
\end{cases}
$$

a. What is a random variable?
b. Find the value of k
c. Find the probability that the values of x would lie between 0 and 1.
d. Is $f(x)$ a probability density function? Justify. 

**4. Probability distribution of a random variable is shown on the table:**

|   x  | -3 | -2 | -1 |  0 |  1 |  2  |
|:----:|:--:|:--:|:--:|:--:|:--:|:---:|
| P(x) |  k | 2k | 3k | 2k | 4k | 0.4 |

a. What is the formula of variance in terms of expectation?
b. Prove expected value is equal to arithmetic mean.
c. Find the value of $k$ and $P(-3 \le X \le 0)$.
d. Determine the $E(X)$ and $V(X)$. 

:::

::: {}
<center><h6>**Group B**</h6></center>

**5. In an industry, 3\% products are found to be defective. A quality control officer collects a sample of 20 items.**

a. What is Bernoulli trial?
b. What is the relationship between Bernoulli and Binomial distribution? 
c. Determine the probability that at least 3 items are defective.
d. Find the probability that no. of defective items would be less than the mean.  

**6. A statistician of a customer care center investigates the calls received and finds that the call center receives 5 calls per hour on average.**

a. What is a Poisson process?
b. Prove that the summation of probability of all possible values of a Poisson distribution is 1. 
c. What is the probability that no less than three calls would be received in an hour?
d. Is the probability of receiving one call greater than that of receiving no calls? Justify mathematically and logically. 



**7. In winter, the probability that it rains on a particular day is 0.015. An analyst observes 100 winter days.**

a. What is an experiment?
b. When can the Poisson distribution be approximated by the Binomial distribution?
c. Find, using Binomial distribution, the probability that  it would not rain at all on the observed days.
d. Find the probability in 3(c) using Poisson distribution. 

**8. For projection of population in a future time period, demographers use simple, geometric or exponential growth technique. Each method has its advantages and disadvantages.**

a. What is simple growth?
b. In geometric growth method, obtain the formula for time required for the population to get doubled [denote rate as r].
c. In exponential method, how much unit of time is required for the population to get tripled? 
d. For projecting (predicting future values), is geometric growth method better than the exponential method? Justify. 

:::

::::

<center>---Good Luck---</center>