---
title: "Binomial Distribution"
author: Abdullah Al Mahmud
date: \today
output: 
  revealjs::revealjs_presentation:
    theme: sky
    transition: zoom
    reveal_plugins: ["chalkboard", "zoom", "menu"]
    reveal_options:
      chalkboard:
        theme: whiteboard
    self_contained: false
    lib_dir: libs
    css: css/styles.css
    includes:
      in_header: css/header.html
---

# Concept

- Success/failure
- Detection of a disease is a success!


## Example

The probability of choosing statistics is `r round(8/50,2)`. If 20 students are randomly selected, what is the probability that 

- at least 5 would choose the subject?
- exactly 2 would choose the subject?
- none will choose? 

## Function

$P(x) = ^nC_x \space p^x(1-p)^{n-x}$

$1-p=q$

> - $p \to$ probability of success
> - $q \to$ probability of failure
> - $n \to$ number of Bernoulli trials
> - $x \to$ no. of success

## Bernoulli Trial

> - Introduced by James Bernoulli
> - Independent trials with dichotomous outcomes (success/failure)
> - Coin toss, disease detection 

## Bernoulli Distribution

$p^xq^{1-x}$ 

If n = 1 in binomial distribution

# Assumptions of Binomial Distribution

> - Trials are independent
> - p, q remain constant for each trial
> - Outcomes are dichotomous
> - X counts number of success

## Properties of Binomial Distribution

> - Mean: $np$
> - Variance: $npq$
> - Skewness, $\beta_1 = \frac{(q-p)^2}{npq}$
> - Kurtosis, $\beta_2 = 3 + \frac{1-6pq}{npq}$

## Derivation of pmf

$P(SF SF \cdots) = P(S) \times P(F) \cdots$

> - $(p \times p \cdots \times p)(\times q \times q \cdots \times q)$
> - $p^xq^{n-x}$
> - $^nC_x \space p^xq^{n-x}$ (any x combination from n)
> - 2 items from a, b, c $\to ab, ac, bc \to \space ^3C_2$

## Derivation of Mean

$\displaystyle E(X) = \sum_{x=0}^n x\cdot p(x)$ (think: why zero?)

> - $0 \cdot p(0) + \cdots$
> - $np\{q^{n-1}+n(n-1)pq^{n-2}+\cdots+p^{n-1}\}$
> - $np(q+p)^{n-1} [binomial \ theorem]$
> - $np$ [p+q=1]

## Uses of Binomial Distribution

> - Quality control
> - Test of fit

## Binomial to Poisson

[See here](prob_ch5_poisson_dist.html#/bionomial-to-poisson)

## Binomial to Noraml

If $n \to \infty$ and $np\ge 5, nq \ge 5$

## Problem 01

The mean and sd of a binomial distribution are 40 and 6. Find 

i) $n,p,q$
ii) $P(x)$
iii) $P(x=0), P(x\ge2), P(x\lt3)$

> - $np = 40$
> - $\sqrt{npq} = 6$
> - $np(1-p)=36 \to 40(1-p)=36 \to 1-p=.9$

## Problem 02

An unbiased coin is tossed 10 times. Find the probability of 

i) 3 heads
ii) at least 2 heads
iii) at most 1 head

## Problem 03

The probability that it rains on a particular day is 0.2. If 10 days are observed, what is the probability that it would rain on

i) all 10 days
ii) no days
iii) at least 2 days
iv) on exactly four days

## Problem 04

In El Clasico, the probability that Barcelona wins is 0.39 and that Real Madrid wins is 0.42. In the next 5 matches, what is the probability that

i) Barcelona wins all the matches?
ii) Real wins all the matches
iii) Barcelona wins at least 2 matches
iv) 2 matches are drawn
v) more than 3 matches are drawn

> - $p_1=$Barca wins, $p_2 =$ Real wins, $p_3 =$Match drawn