---
title: "Poisson Distribution"
author: Abdullah Al Mahmud
date: \today
output: 
  revealjs::revealjs_presentation:
    theme: sky
    transition: zoom
    reveal_plugins: ["chalkboard", "zoom", "menu"]
    reveal_options:
      chalkboard:
        theme: whiteboard
    self_contained: false
    lib_dir: libs
    css: css/styles.css
    includes:
      in_header: css/header.html
---

## Concept

Used in situation where some events occur at certain place or time. 

[See applications](https://en.wikipedia.org/wiki/Poisson_distribution#Occurrence_and_applications)

## Examples

> - No. of car accidents in a month
> - No. of sixes in an innings
> - No. of calls in an hour in a call center
> - No. of bacteria in a $mm^2$
> - No. of defective bolts in a lot (in statistical quality control)
> - No. of particles in a radioactive decay
> - No. of rats in cultivable land
> - No.  of meteorites greater than 1 meter diameter that strike Earth in a year
> - No.  of patients arriving in an emergency room between 10 and 11 pm
> - No.  of laser photons hitting a detector in a particular time interval


## Function

$\displaystyle P(x) = \frac{e^{-\lambda}\lambda^x}{x!}$

> - $e=2.718$ (constant)
> - x: number of occurrences (success)
> - $\lambda$: average no. of events

## Poisson Process

A process involving ..

## Assumptions

> - Occurrences are independent
> - $p \space \propto$Interval
> - another 

## Properties

> - Mean and variance are same ($\lambda$)
> - mgf: $e^\lambda e(^t-1)$
> - If $x_1 \sim Poisson(\lambda_1)$ & $x_2 \sim Poisson(\lambda_1)$, then $(x_1+x_2) \sim Poisson(\lambda_1+\lambda_2)$
> - skewness: $\frac 1 \lambda$ (-ve skew)
> - kurtosis: platykurtic ($1+\frac 1 {\sqrt{\lambda}}$)

# Theorems

## Summation 

$\displaystyle \sum_{i=1}^{\infty} \frac{e^{-\lambda}\lambda^x}{x!}=1$

Prove

## Recurrence 

P(x+1)

## Poisson to Normal

If $\lambda$ is very large.

## Bionomial to  Poisson

- Number of trials, n, is very large: $n \to \infty$
- Probability of success, p, is very low: $p \to 0$
- Mean, $np=\lambda$ finite

## When to Use

- Events that can happen a very large number of time, but happen rarely. 
- That is, they are used in situations that would be more properly represented by a Binomial distribution with a very large n and small p, especially when the exact values of n and p are unknown.

## Difference with Binomial

<div class="container">
<div class="col">
```{r, echo=FALSE}
set.seed(10)
plot(sample(100,80), main="Rats on a filed", xlab = "", ylab = "", axes = F, pch=19, sub = "Could be anywhere, not just on some specific points")
```
</div>
<div class="col">
<small>

> - Binomial counts discrete occurrences among discrete trials (finite attempts)
> - Poisson counts  discrete occurrences among continuous trials (infinite attempts)
> - In Poisson, success can occur at any point of time (or space)
> - Accidents in road (anywhere anytime), knots on a rope

</small>
</div>
</div>

## Difference with Binomial (Contd.)

- Both measure the number of certain random events (or "successes") within a certain frame - Binomial is based on discrete events, while the Poisson is based on continuous events. 
- In a Binomial distribution you have a certain number, n, of "attempts," each of which has probability of success p. 
- With a Poisson distribution, you essentially have infinite attempts, with infinitesimal chance of success. 
- Given a Binomial distribution with some n,p, if you let n→∞ and p→0 in such a way that np→λ, then that distribution approaches a Poisson distribution with parameter λ.

# Problems

## Problem 01

If P(x = 2) = P(x = 3), find

i) parameters
ii) $P(x>0)$
iii) $P(x\le 2)$
iv) $P(x\ge 2)$

## Problem 02

Standard deviation of a Poisson distribution is 4. Find mean and the probabilities in problem 01.

## Problem 03

If $\frac{k\mu^x}{x!}; x = 0, 1, 2, \cdots, \infty,$

k=?

## Problem 04

Overflow floods occur once every 100 years on average. Calculate the probability of k = 0, 1, 2, 3, 4, 5, or 6 overflow floods in a 100-year interval, assuming the Poisson model is appropriate.

> - Because the average event rate is one overflow flood per 100 years, λ = 1

## problem 05

Ugarte and colleagues report that the average number of goals in a World Cup soccer match is approximately 2.5 and the Poisson model is appropriate. Estimate probability of k goals and then k = 0,1,2,3..